In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [89]:
cust = pd.read_csv(r"D:\Python with Data Analysis\PythonProject\PythonProject\CSV_s1\customers.csv")

In [90]:
cust.head()

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state','isActive','createdDate','UpdatedDate'
0,1,Leslie,Bass,F,27,B,37307,endslost@everyma1l.org,Gibson,Dellwood,Y,2017-09-21 12:38:22,2017-10-18 12:12:28
1,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,Y,2017-05-22 05:29:22,2017-10-18 12:12:28
2,3,Marsha,Doyle,F,48,B,80932,arethe53@ma1lbox.net,Perry,Moxadarla,Y,2017-09-03 12:11:29,2017-10-18 12:12:28
3,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,Y,2017-02-16 04:05:35,2017-10-18 12:12:28
4,5,Martha,Combs,F,49,B,83947,camedied@everyma1l.us,Ocilla,Greenwood,Y,2017-05-15 07:34:35,2017-10-18 12:12:28

In [91]:
prod = pd.read_csv(r"D:\Python with Data Analysis\PythonProject\PythonProject\CSV_s1\products.csv")

In [92]:
prod.head()

,'productno','productName','Description','isActive','createdDate','UpdatedDate'
0,1,Product1,pgqorighfa,Y,2017-04-03 07:58:55,2017-10-18 12:12:38
1,2,Product2,lmndaaweth,Y,2017-09-21 12:38:31,2017-10-18 12:12:38
2,3,Product3,urifeubrhh,Y,2017-09-08 10:32:12,2017-10-18 12:12:38
3,4,Product4,rlpcjxfarp,Y,2017-05-22 05:29:27,2017-10-18 12:12:38
4,5,Product5,hzcpozsgfc,Y,2017-02-02 08:40:29,2017-10-18 12:12:38

In [93]:
trans = pd.read_csv(r"D:\Python with Data Analysis\PythonProject\PythonProject\CSV_s1\transactions.csv")

In [94]:
trans.head()

   'txnno'            'txndate'  'custno'  'amount'  'productno' 'spendby'
0        1  2017-10-18 12:31:45       923      2559          376      Card
1        2  2017-10-18 12:31:45       219      1706          151      Card
2        3  2017-10-18 12:31:45       927      3462          707      Cash
3        4  2017-10-18 12:31:45       806       865          539      Card
4        5  2017-10-18 12:31:45       958      2494           25      Card

In [95]:
cust.dtypes

'custno'          int64
'firstname'      object
'lastname'       object
'gender'         object
'age'             int64
'profession'     object
'contactNo'       int64
'emailId'        object
'city'           object
'state'          object
'isActive'       object
'createdDate'    object
'UpdatedDate'    object
dtype: object

In [96]:
prod.dtypes

'productno'       int64
'productName'    object
'Description'    object
'isActive'       object
'createdDate'    object
'UpdatedDate'    object
dtype: object

In [97]:
trans.dtypes

'txnno'         int64
'txndate'      object
'custno'        int64
'amount'        int64
'productno'     int64
'spendby'      object
dtype: object

In [98]:
print(cust.shape)
print(prod.shape)
print(trans.shape)

(1000, 13)
(1000, 6)
(1000, 6)

In [99]:
prod_trans = pd.merge(prod,trans,on="'productno'",how="inner")

In [100]:
prod_trans

,'productno','productName','Description','isActive','createdDate','UpdatedDate','txnno','txndate','custno','amount','spendby'
0,1,Product1,pgqorighfa,Y,2017-04-03 07:58:55,2017-10-18 12:12:38,20,2017-10-18 12:31:45,480,868,Card
1,2,Product2,lmndaaweth,Y,2017-09-21 12:38:31,2017-10-18 12:12:38,416,2017-10-18 12:31:46,217,4628,Card
2,3,Product3,urifeubrhh,Y,2017-09-08 10:32:12,2017-10-18 12:12:38,738,2017-10-18 12:31:46,641,1317,Cash
3,4,Product4,rlpcjxfarp,Y,2017-05-22 05:29:27,2017-10-18 12:12:38,541,2017-10-18 12:31:46,710,2952,Card
4,4,Product4,rlpcjxfarp,Y,2017-05-22 05:29:27,2017-10-18 12:12:38,680,2017-10-18 12:31:46,371,4545,Card
...,...,...,...,...,...,...,...,...,...,...,...
995,995,Product995,fyocaaajef,Y,2017-02-20 11:05:41,2017-10-18 12:12:39,989,2017-10-18 12:31:46,258,4895,Card
996,996,Product996,acvxzpvhyu,Y,2017-09-09 07:49:14,2017-10-18 12:12:39,824,2017-10-18 12:31:46,350,4804,Card
997,997,Product997,eguyggimfm,Y,2017-09-14 12:13:29,2017-10-18 12:12:39,830,2017-10-18 12:31:46,414,3930,Card
998,998,Product998,hagbslxugf,Y,2017-04-20 06:25:03,2017-10-18 12:12:39,253,2017-10-18 12:31:45,652,1272,Card
999,998,Product998,hagbslxugf,Y,2017-04-20 06:25:03,2017-10-18 12:12:39,618,2017-10-18 12:31:46,636,3832,Cash

In [101]:
cust_trans = cust.merge(prod_trans,on="'custno'",how="outer")

In [102]:
cust_trans.head()

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state',...,'productno','productName','Description','isActive'_y,'createdDate'_y,'UpdatedDate'_y,'txnno','txndate','amount','spendby'
0,1,Leslie,Bass,F,27,B,37307,endslost@everyma1l.org,Gibson,Dellwood,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,...,136.0,Product136,ecfldqedud,Y,2017-01-29 04:02:15,2017-10-18 12:12:38,423.0,2017-10-18 12:31:46,4245.0,Cash
2,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,...,842.0,Product842,pjcpkksaav,Y,2017-08-09 01:24:49,2017-10-18 12:12:39,973.0,2017-10-18 12:31:46,4717.0,Card
3,3,Marsha,Doyle,F,48,B,80932,arethe53@ma1lbox.net,Perry,Moxadarla,...,345.0,Product345,trrctekfal,Y,2017-06-17 10:38:18,2017-10-18 12:12:38,146.0,2017-10-18 12:31:45,1730.0,Card
4,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,...,144.0,Product144,vzibyompll,Y,2017-02-07 07:43:43,2017-10-18 12:12:38,620.0,2017-10-18 12:31:46,3926.0,Card

In [103]:
cust_trans.isnull().sum()

'custno'             0
'firstname'          0
'lastname'           0
'gender'             0
'age'                0
'profession'         0
'contactNo'          0
'emailId'            0
'city'               0
'state'              4
'isActive'_x         0
'createdDate'_x      0
'UpdatedDate'_x      0
'productno'        352
'productName'      352
'Description'      352
'isActive'_y       352
'createdDate'_y    352
'UpdatedDate'_y    352
'txnno'            352
'txndate'          352
'amount'           352
'spendby'          352
dtype: int64

In [104]:
cust_trans.dropna(axis=0)

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state',...,'productno','productName','Description','isActive'_y,'createdDate'_y,'UpdatedDate'_y,'txnno','txndate','amount','spendby'
1,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,...,136.0,Product136,ecfldqedud,Y,2017-01-29 04:02:15,2017-10-18 12:12:38,423.0,2017-10-18 12:31:46,4245.0,Cash
2,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,...,842.0,Product842,pjcpkksaav,Y,2017-08-09 01:24:49,2017-10-18 12:12:39,973.0,2017-10-18 12:31:46,4717.0,Card
3,3,Marsha,Doyle,F,48,B,80932,arethe53@ma1lbox.net,Perry,Moxadarla,...,345.0,Product345,trrctekfal,Y,2017-06-17 10:38:18,2017-10-18 12:12:38,146.0,2017-10-18 12:31:45,1730.0,Card
4,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,...,144.0,Product144,vzibyompll,Y,2017-02-07 07:43:43,2017-10-18 12:12:38,620.0,2017-10-18 12:31:46,3926.0,Card
5,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,...,548.0,Product548,wtxnnxgbia,Y,2017-01-22 12:24:15,2017-10-18 12:12:39,990.0,2017-10-18 12:31:46,1892.0,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342,992,Tamara,Shaw,M,32,S,78378,soassert83@hotma1l.org,Vidalia,Railroad,...,825.0,Product825,pksxxazxzh,N,2017-08-10 12:30:58,2017-10-18 12:12:39,599.0,2017-10-18 12:31:46,4663.0,Card
1346,996,Roxanne,Velazquez,M,37,S,57463,warpdays@ma1l2u.co.uk,Crawfordville,Baughman,...,615.0,Product615,glqhilyveo,Y,2017-03-15 09:41:51,2017-10-18 12:12:39,88.0,2017-10-18 12:31:45,2744.0,Card
1347,997,Kristen,Wall,F,20,B,62662,sreynolds64@ma1lbox.org,Stillwell,Beatty,...,5.0,Product5,hzcpozsgfc,Y,2017-02-02 08:40:29,2017-10-18 12:12:38,545.0,2017-10-18 12:31:46,2722.0,Card
1348,997,Kristen,Wall,F,20,B,62662,sreynolds64@ma1lbox.org,Stillwell,Beatty,...,742.0,Product742,mcppmxctyy,Y,2017-08-20 01:09:39,2017-10-18 12:12:39,801.0,2017-10-18 12:31:46,2835.0,Cash
1350,999,Betty,Leon,F,23,B,69268,endfound@somema1l.co.uk,Country Club Estate,Erin,...,789.0,Product789,slnjfchpzt,Y,2017-06-25 04:46:27,2017-10-18 12:12:39,819.0,2017-10-18 12:31:46,4686.0,Cash

In [105]:
cust_trans.isnull().sum()

'custno'             0
'firstname'          0
'lastname'           0
'gender'             0
'age'                0
'profession'         0
'contactNo'          0
'emailId'            0
'city'               0
'state'              4
'isActive'_x         0
'createdDate'_x      0
'UpdatedDate'_x      0
'productno'        352
'productName'      352
'Description'      352
'isActive'_y       352
'createdDate'_y    352
'UpdatedDate'_y    352
'txnno'            352
'txndate'          352
'amount'           352
'spendby'          352
dtype: int64

In [106]:
cust_trans

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state',...,'productno','productName','Description','isActive'_y,'createdDate'_y,'UpdatedDate'_y,'txnno','txndate','amount','spendby'
0,1,Leslie,Bass,F,27,B,37307,endslost@everyma1l.org,Gibson,Dellwood,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,...,136.0,Product136,ecfldqedud,Y,2017-01-29 04:02:15,2017-10-18 12:12:38,423.0,2017-10-18 12:31:46,4245.0,Cash
2,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,...,842.0,Product842,pjcpkksaav,Y,2017-08-09 01:24:49,2017-10-18 12:12:39,973.0,2017-10-18 12:31:46,4717.0,Card
3,3,Marsha,Doyle,F,48,B,80932,arethe53@ma1lbox.net,Perry,Moxadarla,...,345.0,Product345,trrctekfal,Y,2017-06-17 10:38:18,2017-10-18 12:12:38,146.0,2017-10-18 12:31:45,1730.0,Card
4,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,...,144.0,Product144,vzibyompll,Y,2017-02-07 07:43:43,2017-10-18 12:12:38,620.0,2017-10-18 12:31:46,3926.0,Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,997,Kristen,Wall,F,20,B,62662,sreynolds64@ma1lbox.org,Stillwell,Beatty,...,5.0,Product5,hzcpozsgfc,Y,2017-02-02 08:40:29,2017-10-18 12:12:38,545.0,2017-10-18 12:31:46,2722.0,Card
1348,997,Kristen,Wall,F,20,B,62662,sreynolds64@ma1lbox.org,Stillwell,Beatty,...,742.0,Product742,mcppmxctyy,Y,2017-08-20 01:09:39,2017-10-18 12:12:39,801.0,2017-10-18 12:31:46,2835.0,Cash
1349,998,Terry,Blackwell,M,28,S,49457,shipfire@ma1l2u.net,Funston,Winding,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1350,999,Betty,Leon,F,23,B,69268,endfound@somema1l.co.uk,Country Club Estate,Erin,...,789.0,Product789,slnjfchpzt,Y,2017-06-25 04:46:27,2017-10-18 12:12:39,819.0,2017-10-18 12:31:46,4686.0,Cash
1351,1000,Connie,Andrews,M,47,S,78445,dadgenerated@somema1l.co.uk,Montrose,Prame,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
count = cust_trans.groupby(["'custno'","'firstname'","'lastname'"]).size()

In [108]:
purchased = count[count > 3]

In [109]:
purchased

'custno'  'firstname'  'lastname'
4         Alexis       Battle        4
86        Bonnie       McCall        4
167       Alice        Blake         4
187       Alan         Anthony       4
237       Dawn         West          4
241       Derrick      Pearson       5
321       Crystal      Le            4
326       Heidi        Stanley       4
331       Cynthia      Harrison      4
356       Mitchell     Mason         4
391       Keith        Church        5
537       Jake         Bush          4
558       Lois         Todd          4
578       Christine    Murray        4
709       Kyle         Haynes        4
735       James        Payne         4
753       Denise       Stokes        4
828       Katrina      Barber        4
989       Ronald       Mayo          4
dtype: int64

In [116]:
top5_products = cust_trans["'productName'"].value_counts().head(5)

In [117]:
top5_products

'productName'
Product427    5
Product768    5
Product82     5
Product900    5
Product723    4
Name: count, dtype: int64

In [119]:
top5_transactions = cust_trans.sort_values("'amount'", ascending=False).head(5)

In [121]:
top5_transactions

,'custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state',...,'productno','productName','Description','isActive'_y,'createdDate'_y,'UpdatedDate'_y,'txnno','txndate','amount','spendby'
912,670,Vicki,Frank,M,27,S,84305,jcolon28@everyma1l.net,Colquitt,Pennisula,...,509.0,Product509,vxzqcrhjxi,Y,2017-08-21 10:11:09,2017-10-18 12:12:39,557.0,2017-10-18 12:31:46,4996.0,Card
605,448,Joyce,Slater,M,57,S,47613,spittman@somema1l.biz,Metter,Woodbrook,...,427.0,Product427,rnqzbzweys,Y,2017-09-14 10:44:57,2017-10-18 12:12:38,306.0,2017-10-18 12:31:46,4992.0,Cash
404,305,Janice,Valentine,F,62,B,23111,jglover@gma1l.biz,Tarboro,Thornberry,...,549.0,Product549,wzpyhasnxn,Y,2017-09-02 02:06:39,2017-10-18 12:12:39,575.0,2017-10-18 12:31:46,4981.0,Card
300,230,Jean,Singleton,M,64,S,30274,listwhat@gma1l.com,Rockmart,Warwick,...,658.0,Product658,skwqgxqbbf,Y,2017-06-13 06:50:51,2017-10-18 12:12:39,532.0,2017-10-18 12:31:46,4980.0,Card
386,287,Alissa,Roy,F,18,B,85584,bengland@yah00.co.uk,East Dublin,Hideaway,...,685.0,Product685,qoryoiocqa,Y,2017-07-14 12:23:02,2017-10-18 12:12:39,233.0,2017-10-18 12:31:45,4966.0,Card

In [122]:
cust_trans["'profession'"].unique()

array(['B', 'S'], dtype=object)

In [125]:
cust["'age'"].sort_values(ascending=False).head(1)

500    64
Name: 'age', dtype: int64

In [127]:
cust_trans.loc[cust_trans["'custno'"] == 923,
               ["'custno'", "'gender'", "'age'", "'profession'", "'contactNo'", "'productno'", "'productName'", "'txndate'", "'spendby'", "'amount'"]]

,'custno','gender','age','profession','contactNo','productno','productName','txndate','spendby','amount'
1253,923,F,46,B,25436,113.0,Product113,2017-10-18 12:31:46,Card,2303.0
1254,923,F,46,B,25436,376.0,Product376,2017-10-18 12:31:45,Card,2559.0
1255,923,F,46,B,25436,644.0,Product644,2017-10-18 12:31:46,Cash,4553.0

In [132]:
readtrans = pd.read_csv(r"D:\Python with Data Analysis\PythonProject\PythonProject\PSV_s2\transactions.txt")

In [133]:
readtrans.head()

   1|2017-10-18 12:31:45|923|2559|376|Card
0  2|2017-10-18 12:31:45|219|1706|151|Card
1  3|2017-10-18 12:31:45|927|3462|707|Cash
2   4|2017-10-18 12:31:45|806|865|539|Card
3   5|2017-10-18 12:31:45|958|2494|25|Card
4   6|2017-10-18 12:31:45|37|3782|603|Cash

In [130]:
readprod = pd.read_csv(r"D:\Python with Data Analysis\PythonProject\PythonProject\PSV_s2\products.txt")

In [131]:
readprod.head()

  1|Product1|pgqorighfa|Y|2017-04-03 07:58:55|2017-10-18 12:12:38
0  2|Product2|lmndaaweth|Y|2017-09-21 12:38:31|20...
1  3|Product3|urifeubrhh|Y|2017-09-08 10:32:12|20...
2  4|Product4|rlpcjxfarp|Y|2017-05-22 05:29:27|20...
3  5|Product5|hzcpozsgfc|Y|2017-02-02 08:40:29|20...
4  6|Product6|ezhxpqxqdg|Y|2017-01-13 12:47:01|20...

In [134]:
readcst = pd.read_csv(r"D:\Python with Data Analysis\PythonProject\PythonProject\PSV_s2\customers.txt")

In [135]:
readcst.head()

  1|Leslie|Bass|F|27|B|37307|endslost@everyma1l.org|Gibson|Dellwood|Y|2017-09-21 12:38:22|2017-10-18 12:12:28
0  2|Judy|Burks|M|53|S|84759|rfleming@hotma1l.co....
1  3|Marsha|Doyle|F|48|B|80932|arethe53@ma1lbox.n...
2  4|Alexis|Battle|M|27|S|71701|ofcame@ma1lbox.or...
3  5|Martha|Combs|F|49|B|83947|camedied@everyma1l...
4  6|Marilyn|Nguyen|M|57|S|72274|discoveredlist82...

In [137]:
readcstjson = pd.read_json(r"D:\Python with Data Analysis\PythonProject\PythonProject\JSON_s3\customers.json",lines=True)

In [143]:
readcstjson.head()

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdatedDate
0,1,Dai,Noble,2,53,Human Resources,1644101928099,eu.lacus.Quisque@loremac.com,Berlin,Berlin,1,2017-03-01,2018-08-25
1,2,Kay,Wise,2,26,Public Relations,1674031917099,ridiculus@Sednunc.ca,Oldenzaal,Overijssel,2,2017-04-10,2018-08-30
2,3,Amir,Pace,1,43,Customer Relations,1636050509999,quam.Pellentesque@erat.edu,Cobourg,Ontario,2,2017-03-04,2018-09-18
3,4,Sebastian,Lopez,2,32,Customer Relations,1666010108899,magna@venenatis.net,Te Awamutu,NI,1,2016-12-17,2018-09-12
4,5,Brian,Maddox,1,40,Quality Assurance,1646080399299,ac.facilisis@Duis.com,Greater Sudbury,Ontario,2,2017-02-18,2018-05-13

In [139]:
readprodjson = pd.read_json(r"D:\Python with Data Analysis\PythonProject\PythonProject\JSON_s3\products.json",lines=True)

In [144]:
readprodjson.head()

   productno     productName Description  isActive createdDate UpdatedDate
0        100        Vauxhall        four         2  2016-11-21  2017-11-09
1        101          Toyota         six         2  2017-10-03  2017-11-13
2        102  General Motors         two         1  2017-09-18  2017-11-03
3        103         Renault       eight         2  2017-10-05  2017-11-13
4        104        Kenworth       three         1  2017-05-03  2017-11-04

In [141]:
readtransjson = pd.read_json(r"D:\Python with Data Analysis\PythonProject\PythonProject\JSON_s3\transactions.json",lines=True)

In [146]:
readtransjson.head()

   txnno     txndate  custno  amount  productno  spendby
0      1  2018-07-31      71     181         19        2
1      2  2017-04-02      44     401         48        2
2      3  2018-01-31      45    1808         44        2
3      4  2018-04-02      62      65         22        2
4      5  2017-08-17      88    1149         74        2

In [147]:
readcstxml = pd.read_xml(r"D:\Python with Data Analysis\PythonProject\PythonProject\XML_s4\customers.xml")

In [148]:
readcstxml.head()

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdatedDate
0,1,Teegan,Hubbard,2,33,Human Resources,1681121691699,nibh.Quisque@placerat.com,Galashiels,Selkirkshire,1,2016-12-07,2018-09-05
1,2,Deacon,Briggs,2,54,Customer Relations,1631082682999,facilisis.eget@Nullaeu.com,Lens-Saint-Remy,LU,1,2017-04-26,2018-06-04
2,3,Mallory,Shelton,1,57,Customer Relations,1627011572699,Curabitur.ut@Nullatempor.edu,North Shore,NI,1,2017-01-02,2018-08-01
3,4,Quinn,Clements,2,43,Media Relations,1618122268999,metus.Vivamus.euismod@urna.edu,Heredia,H,1,2017-02-11,2018-07-18
4,5,Arthur,Hurst,2,41,Tech Support,1681021022799,in@commodoipsum.org,San Diego,Cartago,2,2017-03-30,2018-05-19

In [149]:
readprodxml = pd.read_xml(r"D:\Python with Data Analysis\PythonProject\PythonProject\XML_s4\products.xml")

In [150]:
readprodxml.head()

   productno     productName Description  isActive createdDate UpdatedDate
0        100  Hyundai Motors       eight         2  2017-10-01  2017-11-04
1        101           Honda       eight         1  2017-04-10  2017-11-11
2        102             GMC       three         2  2017-02-09  2017-11-17
3        103           Lexus       eight         2  2017-06-01  2017-11-04
4        104           Smart        five         2  2017-08-10  2017-11-16

In [151]:
readtxnxml = pd.read_xml(r"D:\Python with Data Analysis\PythonProject\PythonProject\XML_s4\transactions.xml")

In [152]:
readtxnxml.head()

   txnno     txndate  custno  amount  productno  spendby
0      1  2018-09-16       6     576         73        1
1      2  2018-02-11      96    1038         40        2
2      3  2017-06-13      17     673          2        1
3      4  2017-07-25      89    1284        100        2
4      5  2017-06-15       9    1685         56        2